### ISSUE TITLE
HTTP response code parsing

### ISSUE THREAD

**Issue by moonryan2009** [brokensound77/AlertLogic-event-api#13]
Verify that the correct response code is parsed from the packet

**Comment by brokensound77** [comment]
The exact issue is that the regex is catching the response improperly, as it prematurely matches in the previous data (most often from passed POST data).

Will address this soon

**Comment by brokensound77** [comment]
This was addressed in 051711b5b7a7fde767107f09290182647cc51122 in the master-dev branch

After sustained testing, if there are no issues, I will pull to the master branch

**Comment by brokensound77** [comment]
While testing, another issue was discovered where any single occurrences of bytes (2 chars) was not being parsed. This was addressed in ab7a14e7fa81dc193fdde929b46273a006eb3df7. Once this was addressed, the HTTP response code parsing was corrected as well (for the examples tested). Will continue to test before merging.

**Comment by brokensound77** [comment]
Updated and merged in #16
